version: '3.8'

services:
  stresspulse:
    build: .
    container_name: stresspulse
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - TZ=UTC
    command: [
      "/app/stresspulse",
      "-cpu", "50",
      "-drift", "20", 
      "-pattern", "sine",
      "-period", "30s",
      "-log-level", "info",
      "-metrics",
      "-memory",
      "-memory-target", "200",
      "-memory-pattern", "cycle",
      "-fake-logs",
      "-fake-logs-type", "web"
    ]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    user: "1000:1000"
    mem_limit: 512m
    memswap_limit: 512m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - stresspulse

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: 