apiVersion: v1
kind: ConfigMap
metadata:
  name: stresspulse-config
  labels:
    app: stresspulse
data:
  config.yaml: |
    cpu: {{ .Values.config.cpu }}
    drift: {{ .Values.config.drift }}
    pattern: {{ .Values.config.pattern }}
    duration: {{ .Values.config.duration }}
    period: {{ .Values.config.period }}
    workers: {{ .Values.config.workers }}
    logLevel: {{ .Values.config.logLevel }}
    metrics:
      enabled: {{ .Values.config.metrics.enabled }}
      port: {{ .Values.config.metrics.port }} 